MODEL:
  NAME: 'swin_reid'
  PRETRAIN_CHOICE: 'imagenet'
  TRANSFORMER_TYPE: 'swin_base'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 2

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 120
  BASE_LR: 0.0002
  IMS_PER_BATCH: 64

  WEIGHT_DECAY: 1e-4
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 2
  LOG_PERIOD: 50
  EVAL_PERIOD: 2

TEST:
  IMS_PER_BATCH: 256
  RE_RANKING: False
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'logs/swin_reid'